# Enable experience drops for mobs killed by environmental factors
enabled_wither_rose: true
enabled_hot_floor: true
enabled_cramming: true
enabled_lava: true
enabled_fall: true
enabled_pointed_dripstone: true
enabled_stonecutter: true
enabled_iron_golem: true

# Enable debug logging in server console
debug: false

# List world names where experience rewards should not be processed
disabled_worlds:
  - "example_disabled_world"